const weatherActionType = {
    GET_WEATHER: 'GET_WEATHER',
    GET_WEATHER_SUCCESS: 'GET_WEATHER_SUCCESS',
    GET_WEATHER_FAILURE: 'GET_WEATHER_FAILURE',
    REMOVE_SELECTED_SEARCHED_HISTORY_ENTRY: 'REMOVE_SELECTED_SEARCHED_HISTORY_ENTRY',
}

export default weatherActionType;